### ISSUE TITLE
Not getting installed

### ISSUE THREAD

**Issue by syam13** [sgpatil/orientdb-laravel-5#12]
I get "**_\- Conclusion:don't install laravel/framework v5.2.20_**" errors when executing composer update with this package,
I am using Laravel 5.2, below is the link to error for more information.
[https://drive.google.com/file/d/0BybL9l6h3OjTOWk1TjBsNVBFSFU/view?usp=drivesdk](url)

```
"require":{
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laravel/socialite": "^2.0",
        "jenssegers/mongodb": "^2.3",
        "sgpatil/orientdb-laravel-5": "dev-master"

    }
```

Please advise.

**Comment by pin-cnx** [comment]
hum... I plan to upgrade to 5.2 as well.

**Comment by sgpatil** [comment]
Unfortunately current package is not compatible with Laravel 5.2.  I have created separate branch for it but not started coding yet. As I am planning to resolve some big issues in master branch first. Meanwhile you can check the  [Branch 5.2](https://github.com/sgpatil/orientdb-laravel-5/tree/2.0.0) and contribute to it. Thanks...!
