### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by jainamit333** [sgpatil/orientdb-laravel-5#13]
I am trying to setup the orientdb on laravel 5.1
I am getting following error when i am trying to migrate the data.

[BadMethodCallException]  
Call to undefined method Sgpatil\Orientdb\Query\Builder::getListSelect().

I check the class and found there is no method present in this class .

Can you please help.

**Comment by sgpatil** [comment]
Hello @jainamit333 can you please show me the code you trying that generates this error.

**Comment by sgpatil** [comment]
Got the source of error..will resolve it soon..

**Comment by jainamit333** [comment]
Thanks,
