### ISSUE TITLE
how to read and print @rid ? 

### ISSUE THREAD

**Issue by mshanak** [sgpatil/orientdb-laravel-5#18]
hello

i want to print @rid after inserting to database 
i have tried the following 

```
$user["@rid"] // didn’t work
$user->@rid // didn’t work
```

is there a work around?

**Comment by sgpatil** [comment]
Hello @mshanak, `echo $user["@rid"];` is working perfectly for me.

**Comment by nambhd** [comment]
I can not print out @rid too.
Result is 0.
I'm using laravel 5.2.
Please help me check it.
