### ISSUE TITLE
Class 'Sgpatil\Orientdb\QueryException' not found 

### ISSUE THREAD

**Issue by norozap** [sgpatil/orientdb-laravel-5#2]
Hello,

I am running into an issue while running unit tests and php artisan tinker. Whenever I try to do anything using this orientdb wrapper I get :

$test = \MDB\OrientTest::create(['name' => 'Some Name', 'email' => 'some@email.com']);
PHP Fatal error:  Class 'Sgpatil\Orientdb\QueryException' not found in /home/ruser/www/tg/vendor/sgpatil/orientdb-laravel-5/src/Sgpatil/Orientdb/Connection.php on line 463

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Sgpatil\Orientdb\QueryException' not found        

This expects that QueryException.php is located inside src/Sgpatil/Orientdb/ but it doesn't not exist. Is this something on my end?

I have added the required service provider and I'm using the insert record example for testing, but it's not working. Any clues? I am running laravel 5.1.

**Comment by sgpatil** [comment]
Hello @on4wall, I have added `QueryException.php`. Can you please re-run your tests and reply back, also check if Orientdb server is running properly before performing test.

**Comment by norozap** [comment]
Hello @sgpatil , I will update and re-run. I will let you know of the progress.

Thanks!

**Comment by norozap** [comment]
@sgpatil This fixed it! 

Thanks!
