### ISSUE TITLE
Not compatible with Laravel 5.2

### ISSUE THREAD

**Issue by nambhd** [sgpatil/orientdb-laravel-5#21]
"laravel/framework": "5.2._",
        "sgpatil/oriquent": "v5.2.0.1"
Hello,
I'm using Laravel 5.2._ and sgpatil/oriquent v5.2.0.1.
But, when I do this command:
`$user = User::create(['name' => 'Some Name', 'email' => 'some@email.com');`
I receive error: 

> Declaration of Sgpatil\Orientdb\Eloquent\Builder::simplePaginate() should be compatible with Illuminate\Database\Eloquent\Builder::simplePaginate($perPage = NULL, $columns = Array, $pageName = 'page', $page = NULL)

Please help me fix it.

**Comment by sgpatil** [comment]
Hello @lequocnam , We are trying to solve it.

**Comment by sgpatil** [comment]
Hello @lequocnam , Bug has been fixed in master branch. Please install through `dev-master` branch. Let me know if error persist.

**Comment by estevammr** [comment]
Hello, sgpatil! Thank you for the wonderful driver!

I have a return that may be similar to this, can you take my doubt?

> Psy Shell v0.7.2 (PHP 7.0.10 ÔÇö cli) by Justin Hileman
LSAPI\Models\Oriquent\User::all();
PHP warning:  Declaration of Sgpatil\Orientdb\Eloquent\Builder::has($relation, $operator = '>=', $count = 1, $boolean = 'and', Sgpatil\Orientdb\Eloquent\Closure $callback = NULL) should be compatible with Illuminate\Database\Eloquent\Builder::has($relation, $operator = '>=', $count = 1, $boolean = 'and', Closure $callback = NULL) in C:\Users\estev_000\Desktop\php-projects\lsapi\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Eloquent\Builder.php on line 12

My composer.json info

> "laravel/framework" : "5.3.*",
> "sgpatil/oriquent" : "dev-master",

Thanks!!

**Comment by sgpatil** [comment]
Hello @estevammr , Thank you for using this package. At present it does not support Laravel 5.3. We are working on it and will release it soon.

**Comment by estevammr** [comment]
Hello @sgpatil, 

Thanks for the feedback. I'm waiting for the new version ...

Hugs
