### ISSUE TITLE
composer update "sgpatil/orientdb-laravel-5": "dev-master", not found

### ISSUE THREAD

**Issue by gburu98-zz** [sgpatil/orientdb-laravel-5#32]
The composer update does not work, however "composer require" if it works:
![orientdb](https://cloud.githubusercontent.com/assets/12548796/18398569/c666ecac-76a3-11e6-87a1-c12c7de8e523.png)

**Comment by sgpatil** [comment]
Hi @gburu98 , I think there may be some dependency problem, also we have changed `sgpatil/orientdb-laravel-5` to `sgpatil/oriquent`. So it may be the source of problem.
