### ISSUE TITLE
Call to a member function processInsertGetId() on null

### ISSUE THREAD

**Issue by gburu98-zz** [sgpatil/orientdb-laravel-5#33]
Which may be the source of this error?
![error](https://cloud.githubusercontent.com/assets/12548796/18445197/cfc4eba4-78f2-11e6-9240-a6a4c34e3916.png)
![route](https://cloud.githubusercontent.com/assets/12548796/18445205/d7a4fb70-78f2-11e6-91c3-63862b5135a9.png)

try $insertar->save() and return, and does not work...

**Comment by gburu98-zz** [comment]
I needed the \Orientdb in the model, but now I have another error:
![error](https://cloud.githubusercontent.com/assets/12548796/18445766/81bef76c-78f5-11e6-851f-71a013323fb0.png)

**Comment by sgpatil** [comment]
Which Laravel version you are using ?

**Comment by gburu98-zz** [comment]
I am using, Laravel 5.2.31

**Comment by jr2wolfgang** [comment]
This is also my issue now. I don't know why. We have the same issue with gburu98.
At first I also have that processInsertGetId issue but then I just changed it to "extends \Orientdb" and everything went well. But then this simplePaginate becomes the new issue. Any help guys?

**Comment by jr2wolfgang** [comment]
Ok, so I already solved it! I'm using windows and my laravel version is 5.3 (it also works on version 5.2)

Go to this file: vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Eloquent\Builder.php
Line: 371 paste the code below

public function simplePaginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)

So basically, what I did was to add the $page=null on the parameter. Hope this helps anyone

**Comment by sgpatil** [comment]
Closing this as the issue has been resolved in latest release.
