### ISSUE TITLE
Problem with saving a relationship vertex (table)

### ISSUE THREAD

**Issue by jr2wolfgang** [sgpatil/orientdb-laravel-5#34]
I followed the instruction on saving a one to one related vertex found on this article: https://github.com/sgpatil/oriquent/wiki/Relationships

However, there are a lot of issues arising. 

1) Class Has not found. see http://screencast.com/t/eXztkSCqja
![2016-10-07_14-41-50](https://cloud.githubusercontent.com/assets/1019084/19181157/afc24856-8c9d-11e6-9fe7-6e7640ad7d8d.png)

I solve it by commenting line 174 of Sgpatil\Orientdb\Eloquent\Model.php

2) After solving number 1, another issue arise. Call to a member function getTable() on string.
see http://screencast.com/t/Uaua1LjMYx
![2016-10-07_14-45-20](https://cloud.githubusercontent.com/assets/1019084/19181170/c21e9dd8-8c9d-11e6-9fee-1bbd5c23048c.png)

I solve it by temporarily hard coded one of the parameters. On file Sgpatil\Orientdb\Eloquent\Relations\HasOneOrMany.php line 52 i hardcoded the code below:
parent::__construct($query, $parent, 'hasArticle', $localKey);

3) I am stuck at the moment on saving relationship vertex. See http://screencast.com/t/aOcsDaca4
I hope someone can help me figure this out.

![2016-10-07_14-50-24](https://cloud.githubusercontent.com/assets/1019084/19181174/c91ab39c-8c9d-11e6-81d4-b7e449601bcc.png)

**Comment by jr2wolfgang** [comment]
I read in one of your closed issues on how to solve this. I was able to do this now:

public function has_article()
    {
        return $this->hasOne('App\Article', 'App\HasArticle');
    }

But unfortunately, this is my new issue:

`java.lang.IllegalArgumentException: Argument '0' is not a RecordId in form of string. Format must be: <cluster-id>:<cluster-position>#0 C:\web\blog\vendor\sgpatil\orientdb-php\src\Sgpatil\Orientphp\Transport.php(126): Sgpatil\Orientphp\Transport\Curl->makeRequest('POST', '', Array)
#1 C:\web\blog\vendor\sgpatil\orientdb-php\src\Sgpatil\Orientphp\Command.php(67): Sgpatil\Orientphp\Transport->post('', Array, '/batch/blog')
#2 C:\web\blog\vendor\sgpatil\orientdb-php\src\Sgpatil\Orientphp\Client.php(904): Sgpatil\Orientphp\Command->execute()
#3 C:\web\blog\vendor\sgpatil\orientdb-php\src\Sgpatil\Orientphp\Client.php(237): Sgpatil\Orientphp\Client->runCommand(Object(Sgpatil\Orientphp\Command\ExecuteBatchQuery))
#4 C:\web\blog\vendor\sgpatil\orientdb-php\src\Sgpatil\Orientphp\Batch\Query.php(58): Sgpatil\Orientphp\Client->executeBatchQuery(Object(Sgpatil\Orientphp\Batch\Query))
#5 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Connection.php(211): Sgpatil\Orientphp\Batch\Query->getResultSet()
#6 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Connection.php(458): Sgpatil\Orientdb\Connection->Sgpatil\Orientdb\{closure}(Object(Sgpatil\Orientdb\Connection), 'create edge Has...', Array)
#7 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Connection.php(213): Sgpatil\Orientdb\Connection->run('create edge Has...', Array, Object(Closure))
#8 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Query\Builder.php(805): Sgpatil\Orientdb\Connection->insert('create edge Has...', Array)
#9 [internal function]: Sgpatil\Orientdb\Query\Builder->insertRelationship(Object(App\User), Object(App\Article), Object(Sgpatil\Orientphp\Relationship), Array)
#10 C:\web\blog\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1426): call_user_func_array(Array, Array)
#11 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Eloquent\Edges\Relation.php(220): Illuminate\Database\Eloquent\Builder->__call('insertRelations...', Array)
#12 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Eloquent\Edges\Relation.php(220): Sgpatil\Orientdb\Eloquent\Builder->insertRelationship(Object(App\User), Object(App\Article), Object(Sgpatil\Orientphp\Relationship), Array)
#13 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Eloquent\Relations\HasOneOrMany.php(187): Sgpatil\Orientdb\Eloquent\Edges\Relation->save()
#14 C:\web\blog\app\Http\Controllers\PagesController.php(26): Sgpatil\Orientdb\Eloquent\Relations\HasOneOrMany->save(Object(App\Article))
#15 [internal function]: App\Http\Controllers\PagesController->index()
#16 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(80): call_user_func_array(Array, Array)
#17 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('index', Array)
#18 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\PagesController), Object(Illuminate\Routing\Route), 'index')
#19 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\PagesController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#25 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'index')
#26 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#27 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 C:\web\blog\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 C:\web\blog\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 C:\web\blog\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\web\blog\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#58 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#59 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#60 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#62 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#72 C:\web\blog\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#73 {main}#0 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Connection.php(213): Sgpatil\Orientdb\Connection->run('create edge Has...', Array, Object(Closure))
#1 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Query\Builder.php(805): Sgpatil\Orientdb\Connection->insert('create edge Has...', Array)
#2 [internal function]: Sgpatil\Orientdb\Query\Builder->insertRelationship(Object(App\User), Object(App\Article), Object(Sgpatil\Orientphp\Relationship), Array)
#3 C:\web\blog\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1426): call_user_func_array(Array, Array)
#4 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Eloquent\Edges\Relation.php(220): Illuminate\Database\Eloquent\Builder->__call('insertRelations...', Array)
#5 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Eloquent\Edges\Relation.php(220): Sgpatil\Orientdb\Eloquent\Builder->insertRelationship(Object(App\User), Object(App\Article), Object(Sgpatil\Orientphp\Relationship), Array)
#6 C:\web\blog\vendor\sgpatil\oriquent\src\Sgpatil\Orientdb\Eloquent\Relations\HasOneOrMany.php(187): Sgpatil\Orientdb\Eloquent\Edges\Relation->save()
#7 C:\web\blog\app\Http\Controllers\PagesController.php(26): Sgpatil\Orientdb\Eloquent\Relations\HasOneOrMany->save(Object(App\Article))
#8 [internal function]: App\Http\Controllers\PagesController->index()
#9 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(80): call_user_func_array(Array, Array)
#10 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('index', Array)
#11 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\PagesController), Object(Illuminate\Routing\Route), 'index')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\PagesController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#18 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'index')
#19 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#20 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 C:\web\blog\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 C:\web\blog\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 C:\web\blog\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 C:\web\blog\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 C:\web\blog\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 C:\web\blog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 C:\web\blog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 C:\web\blog\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}`

**Comment by sgpatil** [comment]
Hi @jr2wolfgang , I appreciate your exploration. Due to some time unavailability I am not able to look into the project for some weeks. But I will soon resolve the issues and will be back in work. Meanwhile you can fork the project and contribute to it by making PR.

**Comment by jr2wolfgang** [comment]
Thanks @sgpatil for the reply. This technology is a little bit hard to dissect since there are just a few developers who are using it. Some who joined in this community are either testing the waters or just curious with graph DB. I hope you can help me out here. All I wanted to do is just to save the 2 related vertex. Nothing more, nothing less. :(

**Comment by sgpatil** [comment]
@jr2wolfgang , Just solved the issue. Can you please try it once again by reinstalling. I have updated the [wiki page](https://github.com/sgpatil/oriquent/wiki/Relationships)

**Comment by jr2wolfgang** [comment]
@sgpatil I'll try this and will give you feedback. Thanks for the reply
