### ISSUE TITLE
Can't refresh/reset/rollback migrations

### ISSUE THREAD

**Issue by Dalamar** [sgpatil/orientdb-laravel-5#5]
I get `Nothing to rollback.` after executing of `php artisan orient:reset` meanwhile the database remains untouched and all classes remains the same.

I get `Nothing to rollback.` after executing of `php artisan orient:rollback` meanwhile the database remains untouched and all classes remains the same.

I get `Nothing to rollback.` after executing of `php artisan orient:refresh` and exception

```
  [Sgpatil\Orientphp\Exception]
  Error: Unable to create Class
```

meanwhile the database remains untouched and all classes remains the same.

**Comment by DJWassink** [comment]
On a local test all these methods seem to result in the exception being thrown. (I did rename the batch from #6 to number, which did seem to fix the migration table.)

It also seems like the content of the request of the exception reveals a bit more about this issue. The error returned by Orient is `"java.lang.IllegalArgumentException: Class '****' already exists"` so it seems like a drop of a table is actually resulting in a create.

**Comment by sgpatil** [comment]
Hi @DJWassink , yes you are right. The drop method is always calling create class method

**Comment by sgpatil** [comment]
The problem has been solved. Try the updated code and inform

**Comment by Dalamar** [comment]
`php artisan orient:rollback`
`php artisan orient:reset`

They both updates migrations table but they don't delete the schemas that were created during the migration being reseting/rolling back.

`php artisan orient:refresh`
Retuns:

```
Rolled back: 2015_10_28_191606_create_countries_table
Nothing to rollback.
  [Sgpatil\Orientphp\Exception]
  Error: Unable to create Class
```

As the result, migration table is empty but all tables that were created during migrations remain in DB.

**Comment by Dalamar** [comment]
BTW which version of OrientDB do you guys use to test this driver?

**Comment by sgpatil** [comment]
I am using orientdb community 2.0 M1

**Comment by sgpatil** [comment]
Sorry @Dalamar , I just forgot to push changes of orientdb-php . Can you please recheck it using updated code once again.

**Comment by Dalamar** [comment]
Great!
Thanks for quick resolving.
Confirm. Now it works.

**Comment by Dalamar** [comment]
I use following versions for Mac OS X:
1. OrientDB 2.1 Enterprise edition
2. OrientDB 2.2 alpha (from download page)
3. OrientDB 2.2 alpha nightly builds

OrientDB 2.2 alpha (from download page) works fine with column name 'batch' in migrations table.
All other versions I use blaming on the 'batch' property and do not create migration records.

**Comment by sgpatil** [comment]
Closing the issue as it is fixed. Please let me know if you find any problem.
