### ISSUE TITLE
Migration class (table migrations) remains empty after executing migrations

### ISSUE THREAD

**Issue by Dalamar** [sgpatil/orientdb-laravel-5#6]
It happens due to using reserved word 'batch' in query that inserts new record into migration table.
For instance, 

```
insert into migrations (migration, batch) values ('2015_10_12_161815_create_users_table', 1)
```

produces Exception:

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: INSERT INTO migrations (migration, batch) VALUES ('2015_10_12_161815_create_users_table', 1) Encountered " "(" "( "" at line 1, column 24. Was expecting one of: <SELECT> ... <FROM> ... <RETURN> ... <CLUSTER> ...
```

This makes me think that all previous issues regarding the migrations that I created are related to this finding.

**Comment by sgpatil** [comment]
There was some problem in php wrapper for orientdb. I have resolved it. Now migration table is creating along with its fields.
